<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_3e3-gLVdEeueyYy01cW2-g" name="Faturas" author="NoMercy" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_3e3-gbVdEeueyYy01cW2-g" name="Registo das Prestações de Serviço">
      <elements xmi:type="process:Lane" xmi:id="_go5P0LVeEeueyYy01cW2-g" name="Gestor de Serviço" actor="_Z2YaMLVeEeueyYy01cW2-g">
        <elements xmi:type="process:XORGateway" xmi:id="_sGAW4LVfEeueyYy01cW2-g" name="Existem serviços em aberto?" outgoing="_1ko0gLVfEeueyYy01cW2-g _1LLO0LVjEeueyYy01cW2-g" incoming="_qh9KMLVfEeueyYy01cW2-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qhzZMbVfEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qhzZMLVfEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qhzZMrVfEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_1klKILVfEeueyYy01cW2-g" name="Enviar email para os Técnicos sobre os serviços abertos" outgoing="_3HX18MkQEeuHZvio8DfM6Q" incoming="_1ko0gLVfEeueyYy01cW2-g" type="STANDARD">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1klKIrVfEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1klKIbVfEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1klKI7VfEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_N18NkMqbEeuay6daAqWfHw" name="Mandar email" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_N18NkcqbEeuay6daAqWfHw" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NksqbEeuay6daAqWfHw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_N18Nk8qbEeuay6daAqWfHw" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NlMqbEeuay6daAqWfHw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_N18NlcqbEeuay6daAqWfHw" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NlsqbEeuay6daAqWfHw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_N18Nl8qbEeuay6daAqWfHw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NmMqbEeuay6daAqWfHw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_N18NmcqbEeuay6daAqWfHw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NmsqbEeuay6daAqWfHw" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_N18Nm8qbEeuay6daAqWfHw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NnMqbEeuay6daAqWfHw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_N18NncqbEeuay6daAqWfHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NnsqbEeuay6daAqWfHw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_N18Nn8qbEeuay6daAqWfHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NoMqbEeuay6daAqWfHw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_N18NocqbEeuay6daAqWfHw" name="noreply@prestaser.com" content="noreply@prestaser.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NosqbEeuay6daAqWfHw" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_N18No8qbEeuay6daAqWfHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NpMqbEeuay6daAqWfHw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_N18NpcqbEeuay6daAqWfHw" name="to()" content="import com.company.model.Pedido&#xD;&#xA;&#xD;&#xA;Pedido pedido = listaPedidosAbertos.get(iterador)&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;return pedido.tecnico" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3RbCUMqbEeuay6daAqWfHw" name="listaPedidosAbertos" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido"/>
                  <referencedElements xmi:type="process:Data" xmi:id="_3RbCUcqbEeuay6daAqWfHw" name="iterador" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NpsqbEeuay6daAqWfHw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_N18Np8qbEeuay6daAqWfHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NqMqbEeuay6daAqWfHw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_N18NqcqbEeuay6daAqWfHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NqsqbEeuay6daAqWfHw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_N18Nq8qbEeuay6daAqWfHw" name="Faturas" content="Faturas" interpreter="GROOVY" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NrMqbEeuay6daAqWfHw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_N18NrcqbEeuay6daAqWfHw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NrsqbEeuay6daAqWfHw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_N18Nr8qbEeuay6daAqWfHw" name="&lt;pattern-expression>" content="&lt;p>As faturas foram lan&amp;ccedil;adas.&lt;/p>&#xA;&#xA;&lt;p>O pedido ${listaPedidosAbertos.get(iterador).id.toString()} n&amp;atilde;o consta nas faturas.&lt;/p>&#xA;" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_HtozsMt5Eeuskqtd-X0x2w" name="listaPedidosAbertos.get(iterador).id.toString()" content="listaPedidosAbertos.get(iterador).id.toString()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_Htozsct5Eeuskqtd-X0x2w" name="iterador" content="iterador" type="TYPE_VARIABLE" returnType="java.lang.Integer">
                      <referencedElements xmi:type="process:Data" xmi:id="_Htozsst5Eeuskqtd-X0x2w" name="iterador" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
                    </referencedElements>
                    <referencedElements xmi:type="expression:Expression" xmi:id="_Htozs8t5Eeuskqtd-X0x2w" name="listaPedidosAbertos" content="listaPedidosAbertos" type="TYPE_VARIABLE" returnType="java.util.List">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_HtoztMt5Eeuskqtd-X0x2w" name="listaPedidosAbertos" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido"/>
                    </referencedElements>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NsMqbEeuay6daAqWfHw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_N18NscqbEeuay6daAqWfHw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NssqbEeuay6daAqWfHw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_N18Ns8qbEeuay6daAqWfHw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NtMqbEeuay6daAqWfHw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_N18NtcqbEeuay6daAqWfHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N18NtsqbEeuay6daAqWfHw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_N18Nt8qbEeuay6daAqWfHw"/>
              </parameters>
            </configuration>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_kHvV4MYgEeudAOO29mXQjQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_kHvV4cYgEeudAOO29mXQjQ" name="iterador" content="iterador" type="TYPE_VARIABLE" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_JQyFEMYhEeudAOO29mXQjQ" name="iterador" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_kHvV4sYgEeudAOO29mXQjQ" name="incrementa()" content="return iterador+1" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_NKMmoMYhEeudAOO29mXQjQ" name="iterador" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_kHvV48YgEeudAOO29mXQjQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1klKJLVfEeueyYy01cW2-g" name="loopWhile()" content="iterador &lt; numeroPedidosAbertos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
            <referencedElements xmi:type="process:Data" xmi:id="_-G3pcMqWEeuay6daAqWfHw" name="iterador" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            <referencedElements xmi:type="process:Data" xmi:id="_-G3pccqWEeuay6daAqWfHw" name="numeroPedidosAbertos" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
          </loopCondition>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1klKJbVfEeueyYy01cW2-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1klKJrVfEeueyYy01cW2-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1klKKLVfEeueyYy01cW2-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1klKJ7VfEeueyYy01cW2-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_33XvULVjEeueyYy01cW2-g" name="Gateway3" outgoing="_6L4IkLVjEeueyYy01cW2-g" incoming="_1LLO0LVjEeueyYy01cW2-g _3HX18MkQEeuHZvio8DfM6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1LIykrVjEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1LIykbVjEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1LIyk7VjEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_glEfMMOVEeu9G7kJfwO5Gg" name="Validar que se todas as prestações de serviço estão terminadas" outgoing="_qh9KMLVfEeueyYy01cW2-g" incoming="_j6HloMt7Eeuskqtd-X0x2w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3e3-iLVdEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3e4lkLVdEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3e4lkbVdEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Gn1aYMqWEeuay6daAqWfHw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Gn2BcMqWEeuay6daAqWfHw" name="listaPedidosAbertos" content="listaPedidosAbertos" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_HIIEAMqWEeuay6daAqWfHw" name="listaPedidosAbertos" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Gn2BccqWEeuay6daAqWfHw" name="getPedidosAbertos()" content="pedidoDAO.findPedidosAbertos(0, 999)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="expression:Expression" xmi:id="_iKeQAMqWEeuay6daAqWfHw" name="pedidoDAO" content="pedidoDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.PedidoDAO" returnTypeFixed="true"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Gn2BcsqWEeuay6daAqWfHw" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_zpx_gMqWEeuay6daAqWfHw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_zpx_gcqWEeuay6daAqWfHw" name="numeroPedidosAbertos" content="numeroPedidosAbertos" type="TYPE_VARIABLE" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_0GvBQMqWEeuay6daAqWfHw" name="numeroPedidosAbertos" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_zpx_gsqWEeuay6daAqWfHw" name="sizeListaPedidosAbertos()" content="listaPedidosAbertos.size()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6x1AQMqWEeuay6daAqWfHw" name="listaPedidosAbertos" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_zpx_g8qWEeuay6daAqWfHw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3e4lkrVdEeueyYy01cW2-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3e4lk7VdEeueyYy01cW2-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_3e4llLVdEeueyYy01cW2-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_3e4llbVdEeueyYy01cW2-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_3e4llrVdEeueyYy01cW2-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartTimerEvent" xmi:id="_xr-sEMsEEeuVH99PbiCVIw" name="No ínicio do mês" outgoing="_j6HloMt7Eeuskqtd-X0x2w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xr-sEssEEeuVH99PbiCVIw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xr-sEcsEEeuVH99PbiCVIw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xr_TIMsEEeuVH99PbiCVIw" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_yp7iEMsEEeuVH99PbiCVIw" name="0 0 18 1 1/1 ? *" content="0 0 18 1 1/1 ? *" interpreter="GROOVY"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_hEauMLVeEeueyYy01cW2-g" name="Contabilidade/Finanças" actor="_3e4lorVdEeueyYy01cW2-g">
        <elements xmi:type="process:ServiceTask" xmi:id="_6L1FQLVjEeueyYy01cW2-g" name="Retirar listagem do ERP com as intervenções do mês anterior" outgoing="_HlCFwMkSEeuHZvio8DfM6Q" incoming="_6L4IkLVjEeueyYy01cW2-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6L1FQrVjEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6L1FQbVjEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6L1FQ7VjEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_UY6IIMqXEeuay6daAqWfHw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_UY6IIcqXEeuay6daAqWfHw" name="listaPedidosCompletados" content="listaPedidosCompletados" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_U299IMqXEeuay6daAqWfHw" name="listaPedidosCompletados" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_UY6IIsqXEeuay6daAqWfHw" name="getListaPedidosCompletados()" content="pedidoDAO.findPedidosCompletados(0, 999)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="expression:Expression" xmi:id="_r1rUkMqXEeuay6daAqWfHw" name="pedidoDAO" content="pedidoDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.PedidoDAO" returnTypeFixed="true"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_UY6II8qXEeuay6daAqWfHw" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mEMIAMqgEeuay6daAqWfHw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mEMIAcqgEeuay6daAqWfHw" name="numeroPedidosFechados" content="numeroPedidosFechados" type="TYPE_VARIABLE" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_m2Na0MqgEeuay6daAqWfHw" name="numeroPedidosFechados" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mEMIAsqgEeuay6daAqWfHw" name="sizePedidosCompletados()" content="listaPedidosCompletados.size()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rHHPUMqgEeuay6daAqWfHw" name="listaPedidosCompletados" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mEMIA8qgEeuay6daAqWfHw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6L1FRLVjEeueyYy01cW2-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6L1FRbVjEeueyYy01cW2-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6L1FRrVjEeueyYy01cW2-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6L1FSLVjEeueyYy01cW2-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6L1FR7VjEeueyYy01cW2-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_8mOEELVjEeueyYy01cW2-g" name="End4" incoming="_NBM_EMt5Eeuskqtd-X0x2w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8mOEErVjEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8mOEEbVjEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8mOEE7VjEeueyYy01cW2-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_OhdVIMquEeu5_vz_SfX0Jg" name="Guardar listagem para faturas" outgoing="_sNUJ8MrCEeuyAPbXmyzj0w" incoming="_HlCFwMkSEeuHZvio8DfM6Q" type="STANDARD">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HlAQkskSEeuHZvio8DfM6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HlAQkckSEeuHZvio8DfM6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HlAQk8kSEeuHZvio8DfM6Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_R_Xu0MqgEeuay6daAqWfHw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_R_Xu0cqgEeuay6daAqWfHw" name="iteradorPedidosFechados" content="iteradorPedidosFechados" type="TYPE_VARIABLE" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_0BwPEMqgEeuay6daAqWfHw" name="iteradorPedidosFechados" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_R_Xu0sqgEeuay6daAqWfHw" name="incrementador()" content="return iteradorPedidosFechados +1" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_5R9kcMqgEeuay6daAqWfHw" name="iteradorPedidosFechados" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_R_Xu08qgEeuay6daAqWfHw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HlAQlMkSEeuHZvio8DfM6Q" name="loopParaFaturas()" content="iteradorPedidosFechados &lt; numeroPedidosFechados" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
            <referencedElements xmi:type="process:Data" xmi:id="_wYQY0MqgEeuay6daAqWfHw" name="iteradorPedidosFechados" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            <referencedElements xmi:type="process:Data" xmi:id="_wYQY0cqgEeuay6daAqWfHw" name="numeroPedidosFechados" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
          </loopCondition>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HlAQlckSEeuHZvio8DfM6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HlAQlskSEeuHZvio8DfM6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HlAQmMkSEeuHZvio8DfM6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HlAQl8kSEeuHZvio8DfM6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_SUwnoMquEeu5_vz_SfX0Jg" subprocessTarget="pedido" assignationType="Data">
            <processSource xmi:type="expression:Expression" xmi:id="_SUwnocquEeu5_vz_SfX0Jg" name="listaPedidosCompletados" content="listaPedidosCompletados.get(iteradorPedidosFechados)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_thISUMquEeu5_vz_SfX0Jg" name="listaPedidosCompletados" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido"/>
              <referencedElements xmi:type="process:Data" xmi:id="_thISUcquEeu5_vz_SfX0Jg" name="iteradorPedidosFechados" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            </processSource>
          </inputMappings>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_OhdVJMquEeu5_vz_SfX0Jg" name="Gerar dados de fatura" content="Gerar dados de fatura" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_OhdVJcquEeu5_vz_SfX0Jg" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_NBD1IMt5Eeuskqtd-X0x2w" name="Enviar email para a contabilidade" outgoing="_NBM_EMt5Eeuskqtd-X0x2w" incoming="_sNUJ8MrCEeuyAPbXmyzj0w" type="STANDARD">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NBEcMct5Eeuskqtd-X0x2w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NBEcMMt5Eeuskqtd-X0x2w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NBEcMst5Eeuskqtd-X0x2w" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_i4Lc8Mt6Eeuskqtd-X0x2w" name="EnviarEmailContabilidade" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_i4MEAMt6Eeuskqtd-X0x2w" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEAct6Eeuskqtd-X0x2w" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEAst6Eeuskqtd-X0x2w" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEA8t6Eeuskqtd-X0x2w" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEBMt6Eeuskqtd-X0x2w" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEBct6Eeuskqtd-X0x2w" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEBst6Eeuskqtd-X0x2w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEB8t6Eeuskqtd-X0x2w" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_i4MECMt6Eeuskqtd-X0x2w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MECct6Eeuskqtd-X0x2w" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_i4MECst6Eeuskqtd-X0x2w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEC8t6Eeuskqtd-X0x2w" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEDMt6Eeuskqtd-X0x2w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEDct6Eeuskqtd-X0x2w" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEDst6Eeuskqtd-X0x2w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MED8t6Eeuskqtd-X0x2w" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEEMt6Eeuskqtd-X0x2w" name="noreply@prestaser.com" content="noreply@prestaser.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEEct6Eeuskqtd-X0x2w" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEEst6Eeuskqtd-X0x2w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEE8t6Eeuskqtd-X0x2w" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEFMt6Eeuskqtd-X0x2w" name="to()" content="listaContabilidade.get(iteratorListaContabilidade).userName" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:JavaObjectData" xmi:id="_i4MEFct6Eeuskqtd-X0x2w" name="listaContabilidade" multiple="true" dataType="_3e4lubVdEeueyYy01cW2-g" className="org.bonitasoft.engine.identity.User"/>
                  <referencedElements xmi:type="process:Data" xmi:id="_i4MEFst6Eeuskqtd-X0x2w" name="iteratorListaContabilidade" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEF8t6Eeuskqtd-X0x2w" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEGMt6Eeuskqtd-X0x2w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEGct6Eeuskqtd-X0x2w" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEGst6Eeuskqtd-X0x2w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEG8t6Eeuskqtd-X0x2w" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEHMt6Eeuskqtd-X0x2w" name="Faturas lançadas" content="Faturas lançadas" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEHct6Eeuskqtd-X0x2w" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEHst6Eeuskqtd-X0x2w" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEH8t6Eeuskqtd-X0x2w" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEIMt6Eeuskqtd-X0x2w" name="&lt;pattern-expression>" content="&lt;p>As faturas do m&amp;ecirc;s passado, foram lan&amp;ccedil;adas com sucesso.&lt;/p>&#xA;" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEIct6Eeuskqtd-X0x2w" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_i4MEIst6Eeuskqtd-X0x2w"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEI8t6Eeuskqtd-X0x2w" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEJMt6Eeuskqtd-X0x2w" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEJct6Eeuskqtd-X0x2w" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_i4MEJst6Eeuskqtd-X0x2w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i4MEJ8t6Eeuskqtd-X0x2w" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_i4MEKMt6Eeuskqtd-X0x2w"/>
              </parameters>
            </configuration>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_pNyUIMt6Eeuskqtd-X0x2w">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pNyUIct6Eeuskqtd-X0x2w" name="iteratorListaContabilidade" content="iteratorListaContabilidade" type="TYPE_VARIABLE" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_pv3GcMt6Eeuskqtd-X0x2w" name="iteratorListaContabilidade" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pNyUIst6Eeuskqtd-X0x2w" name="iterador++" content="return iteratorListaContabilidade + 1" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_s1cXUMt6Eeuskqtd-X0x2w" name="iteratorListaContabilidade" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pNyUI8t6Eeuskqtd-X0x2w" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_NBEcM8t5Eeuskqtd-X0x2w" name="loopWhile()" content="iteratorListaContabilidade &lt; listaContabilidade.size()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
            <referencedElements xmi:type="process:Data" xmi:id="_RrMMgMt6Eeuskqtd-X0x2w" name="iteratorListaContabilidade" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            <referencedElements xmi:type="process:JavaObjectData" xmi:id="_RrMzkMt6Eeuskqtd-X0x2w" name="listaContabilidade" multiple="true" dataType="_3e4lubVdEeueyYy01cW2-g" className="org.bonitasoft.engine.identity.User"/>
          </loopCondition>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_NBEcNMt5Eeuskqtd-X0x2w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_NBEcNct5Eeuskqtd-X0x2w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_NBFDQMt5Eeuskqtd-X0x2w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_NBEcNst5Eeuskqtd-X0x2w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_Clf40MYhEeudAOO29mXQjQ" name="iterador" dataType="_3e4ltbVdEeueyYy01cW2-g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Clf40cYhEeudAOO29mXQjQ" name="0" content="0" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_6mIYgMqUEeuay6daAqWfHw" name="listaPedidosCompletados" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6mIYgcqUEeuay6daAqWfHw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_0y0goMqVEeuay6daAqWfHw" name="listaPedidosAbertos" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido">
        <defaultValue xmi:type="expression:Expression" xmi:id="_0y0gocqVEeuay6daAqWfHw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_yekJkMqWEeuay6daAqWfHw" name="numeroPedidosAbertos" dataType="_3e4ltbVdEeueyYy01cW2-g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_yekJkcqWEeuay6daAqWfHw" name="0" content="0" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_iVvgUMqgEeuay6daAqWfHw" name="iteradorPedidosFechados" dataType="_3e4ltbVdEeueyYy01cW2-g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_iVvgUcqgEeuay6daAqWfHw" name="0" content="0" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_k17lIMqgEeuay6daAqWfHw" name="numeroPedidosFechados" dataType="_3e4ltbVdEeueyYy01cW2-g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_k17lIcqgEeuay6daAqWfHw" name="0" content="0" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_dL0zkMt5Eeuskqtd-X0x2w" name="listaContabilidade" multiple="true" dataType="_3e4lubVdEeueyYy01cW2-g" className="org.bonitasoft.engine.identity.User">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dL0zkct5Eeuskqtd-X0x2w" name="init_listaContabilidade()" content="import org.bonitasoft.engine.identity.UserCriterion&#xD;&#xA;&#xD;&#xA;def group = apiAccessor.identityAPI.getGroupByPath(&quot;contabilidade&quot;)&#xD;&#xA;&#xD;&#xA;return apiAccessor.identityAPI.getUsersInGroup(group.getId(), 0, 9999, UserCriterion.FIRST_NAME_ASC)&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
          <referencedElements xmi:type="expression:Expression" xmi:id="_xBevYMt5Eeuskqtd-X0x2w" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
        </defaultValue>
      </data>
      <data xmi:type="process:Data" xmi:id="_0uMRsMt5Eeuskqtd-X0x2w" name="iteratorListaContabilidade" dataType="_3e4ltbVdEeueyYy01cW2-g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_0uMRsct5Eeuskqtd-X0x2w" name="0" content="0" returnType="java.lang.Integer"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_3e4lm7VdEeueyYy01cW2-g">
        <targetForm xmi:type="expression:Expression" xmi:id="_0BOzIMt7Eeuskqtd-X0x2w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_3e4lnbVdEeueyYy01cW2-g">
        <targetForm xmi:type="expression:Expression" xmi:id="_3e4lnrVdEeueyYy01cW2-g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qh9KMLVfEeueyYy01cW2-g" target="_sGAW4LVfEeueyYy01cW2-g" source="_glEfMMOVEeu9G7kJfwO5Gg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qh9KMbVfEeueyYy01cW2-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_qh9KMrVfEeueyYy01cW2-g" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1ko0gLVfEeueyYy01cW2-g" name="Sim" target="_1klKILVfEeueyYy01cW2-g" source="_sGAW4LVfEeueyYy01cW2-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1ko0gbVfEeueyYy01cW2-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_1ko0grVfEeueyYy01cW2-g" name="newScript()" content="numeroPedidosAbertos>0" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_QOrKEMqcEeuay6daAqWfHw" name="numeroPedidosAbertos" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1LLO0LVjEeueyYy01cW2-g" name="Não" target="_33XvULVjEeueyYy01cW2-g" source="_sGAW4LVfEeueyYy01cW2-g" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1LLO0bVjEeueyYy01cW2-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_1LLO0rVjEeueyYy01cW2-g" name="false" content="false" interpreter="GROOVY" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6L4IkLVjEeueyYy01cW2-g" target="_6L1FQLVjEeueyYy01cW2-g" source="_33XvULVjEeueyYy01cW2-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6L4IkbVjEeueyYy01cW2-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_6L4IkrVjEeueyYy01cW2-g" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3HX18MkQEeuHZvio8DfM6Q" target="_33XvULVjEeueyYy01cW2-g" source="_1klKILVfEeueyYy01cW2-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3HX18ckQEeuHZvio8DfM6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_3HX18skQEeuHZvio8DfM6Q" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HlCFwMkSEeuHZvio8DfM6Q" target="_OhdVIMquEeu5_vz_SfX0Jg" source="_6L1FQLVjEeueyYy01cW2-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HlCFwckSEeuHZvio8DfM6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_HlCFwskSEeuHZvio8DfM6Q" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sNUJ8MrCEeuyAPbXmyzj0w" target="_NBD1IMt5Eeuskqtd-X0x2w" source="_OhdVIMquEeu5_vz_SfX0Jg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sNXNQMrCEeuyAPbXmyzj0w"/>
        <condition xmi:type="expression:Expression" xmi:id="_sNXNQcrCEeuyAPbXmyzj0w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NBM_EMt5Eeuskqtd-X0x2w" target="_8mOEELVjEeueyYy01cW2-g" source="_NBD1IMt5Eeuskqtd-X0x2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NBM_Ect5Eeuskqtd-X0x2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_NBM_Est5Eeuskqtd-X0x2w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_j6HloMt7Eeuskqtd-X0x2w" target="_glEfMMOVEeu9G7kJfwO5Gg" source="_xr-sEMsEEeuVH99PbiCVIw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_j6Hloct7Eeuskqtd-X0x2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_j6Hlost7Eeuskqtd-X0x2w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_3e4lorVdEeueyYy01cW2-g" name="Contabilidade/Finanças"/>
      <actors xmi:type="process:Actor" xmi:id="_Wvh-ALVeEeueyYy01cW2-g" name="Técnicos"/>
      <actors xmi:type="process:Actor" xmi:id="_Z2YaMLVeEeueyYy01cW2-g" name="Gestor de Serviço" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_3e4lo7VdEeueyYy01cW2-g"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3e4lpLVdEeueyYy01cW2-g">
        <name xmi:type="expression:Expression" xmi:id="_3e4lpbVdEeueyYy01cW2-g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3e4lprVdEeueyYy01cW2-g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3e4lp7VdEeueyYy01cW2-g">
        <name xmi:type="expression:Expression" xmi:id="_3e4lqLVdEeueyYy01cW2-g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3e4lqbVdEeueyYy01cW2-g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3e4lqrVdEeueyYy01cW2-g">
        <name xmi:type="expression:Expression" xmi:id="_3e4lq7VdEeueyYy01cW2-g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3e4lrLVdEeueyYy01cW2-g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3e4lrbVdEeueyYy01cW2-g">
        <name xmi:type="expression:Expression" xmi:id="_3e4lrrVdEeueyYy01cW2-g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3e4lr7VdEeueyYy01cW2-g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3e4lsLVdEeueyYy01cW2-g">
        <name xmi:type="expression:Expression" xmi:id="_3e4lsbVdEeueyYy01cW2-g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3e4lsrVdEeueyYy01cW2-g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_3yWf8MqtEeu5_vz_SfX0Jg" name="Gerar dados de fatura">
      <elements xmi:type="process:StartEvent" xmi:id="_L51LkMquEeu5_vz_SfX0Jg" name="Start1" outgoing="_Hjnj0MqvEeu5_vz_SfX0Jg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_L51LksquEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_L51LkcquEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_L51Lk8quEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_LS6gEMqvEeu5_vz_SfX0Jg" name="Retirar intervenções do pedido" outgoing="_UqMGkMqxEeu5_vz_SfX0Jg" incoming="_Hjnj0MqvEeu5_vz_SfX0Jg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_GuddccqvEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_GuddcMqvEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_GuddcsqvEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_hxOzgMrsEeulHv9W8VSu9Q">
          <leftOperand xmi:type="expression:Expression" xmi:id="_hxOzgcrsEeulHv9W8VSu9Q" name="listaIntervencoes" content="listaIntervencoes" type="TYPE_VARIABLE" returnType="java.util.List">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_i5yXAMrsEeulHv9W8VSu9Q" name="listaIntervencoes" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Intervencao"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_hxOzgsrsEeulHv9W8VSu9Q" name="newScript()" content="intervencaoDAO.findByPedido(pedido.id, 0, 999)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
            <referencedElements xmi:type="expression:Expression" xmi:id="_ksDl4MrsEeulHv9W8VSu9Q" name="intervencaoDAO" content="intervencaoDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.IntervencaoDAO" returnTypeFixed="true"/>
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ksDl4crsEeulHv9W8VSu9Q" name="pedido" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_hxOzg8rsEeulHv9W8VSu9Q" type="ASSIGNMENT"/>
        </operations>
        <operations xmi:type="expression:Operation" xmi:id="_pWVksMrhEeuCxpnbvV_u_Q">
          <leftOperand xmi:type="expression:Expression" xmi:id="_pWVkscrhEeuCxpnbvV_u_Q" name="sizeLista" content="sizeLista" type="TYPE_VARIABLE" returnType="java.lang.Integer">
            <referencedElements xmi:type="process:Data" xmi:id="_uIoPAMrhEeuCxpnbvV_u_Q" name="sizeLista" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_pWVkssrhEeuCxpnbvV_u_Q" name="getSizeLista()" content="listaIntervencoes.size()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yN2X8MrhEeuCxpnbvV_u_Q" name="listaIntervencoes" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Intervencao"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_pWVks8rhEeuCxpnbvV_u_Q" type="ASSIGNMENT"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_Guddc8qvEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_GudddMqvEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GudddcqvEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_Guddd8qvEeu5_vz_SfX0Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_GudddsqvEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_UqDjsMqxEeu5_vz_SfX0Jg" name="Gerar dados de insereção de fatura" outgoing="_UtL6wMqyEeu5_vz_SfX0Jg" incoming="_UqMGkMqxEeu5_vz_SfX0Jg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_UqEx0MqxEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_UqEKwMqxEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_UqEx0cqxEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_B7RT4MqyEeu5_vz_SfX0Jg">
          <leftOperand xmi:type="expression:Expression" xmi:id="_B7RT4cqyEeu5_vz_SfX0Jg" name="clientId" content="clientId" type="TYPE_VARIABLE">
            <referencedElements xmi:type="process:Data" xmi:id="_CbJGwMqyEeu5_vz_SfX0Jg" name="clientId" dataType="_3e4luLVdEeueyYy01cW2-g"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_B7RT4sqyEeu5_vz_SfX0Jg" name="getClientId()" content="pedido.cliente.id" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_unYWcMqzEeu5_vz_SfX0Jg" name="pedido" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_B7RT48qyEeu5_vz_SfX0Jg" type="ASSIGNMENT"/>
        </operations>
        <operations xmi:type="expression:Operation" xmi:id="_GR4HwMqyEeu5_vz_SfX0Jg">
          <leftOperand xmi:type="expression:Expression" xmi:id="_GR4HwcqyEeu5_vz_SfX0Jg" name="valorContrato" content="valorContrato" type="TYPE_VARIABLE" returnType="java.lang.Double">
            <referencedElements xmi:type="process:Data" xmi:id="_G7BycMqyEeu5_vz_SfX0Jg" name="valorContrato" dataType="_3e4lt7VdEeueyYy01cW2-g"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_GR4HwsqyEeu5_vz_SfX0Jg" name="getValorContrato()" content="pedido.cliente.valorContrato" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Double">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_MgHLoMqyEeu5_vz_SfX0Jg" name="pedido" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_GR4Hw8qyEeu5_vz_SfX0Jg" type="ASSIGNMENT"/>
        </operations>
        <operations xmi:type="expression:Operation" xmi:id="_MsnWkMqyEeu5_vz_SfX0Jg">
          <leftOperand xmi:type="expression:Expression" xmi:id="_MsnWkcqyEeu5_vz_SfX0Jg" name="valorTotal" content="valorTotal" type="TYPE_VARIABLE" returnType="java.lang.Double">
            <referencedElements xmi:type="process:Data" xmi:id="_ayrK8Mq1Eeu5_vz_SfX0Jg" name="valorTotal" dataType="_3e4lt7VdEeueyYy01cW2-g"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_MsnWksqyEeu5_vz_SfX0Jg" name="generateValorTotal()" content="import java.util.logging.Logger&#xD;&#xA;&#xD;&#xA;//Logger l = Logger.getLogger(&quot;.l.&quot;)&#xD;&#xA;&#xD;&#xA;Double r = valorContrato*listaIntervencoes.size()&#xD;&#xA;&#xD;&#xA;//l.severe(r)&#xD;&#xA;&#xD;&#xA;return r" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Double">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8l_NEMq4Eeu5_vz_SfX0Jg" name="listaIntervencoes" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Intervencao"/>
            <referencedElements xmi:type="process:Data" xmi:id="_8l_NEcq4Eeu5_vz_SfX0Jg" name="valorContrato" dataType="_3e4lt7VdEeueyYy01cW2-g"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_MsnWk8qyEeu5_vz_SfX0Jg" type="ASSIGNMENT"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_UqEx0sqxEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_UqEx08qxEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UqEx1MqxEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_UqEx1sqxEeu5_vz_SfX0Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_UqEx1cqxEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_UtHCQMqyEeu5_vz_SfX0Jg" name="Inserir dados fatura" outgoing="_9oYgYMrHEeu5_vz_SfX0Jg" incoming="_UtL6wMqyEeu5_vz_SfX0Jg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_UtHpUcqyEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_UtHpUMqyEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_UtHpUsqyEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <connectors xmi:type="process:Connector" xmi:id="_zk510MqyEeu5_vz_SfX0Jg" name="insertFatura" definitionId="database-mysql" event="ON_ENTER" definitionVersion="1.0.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_zk510cqyEeu5_vz_SfX0Jg" definitionId="database-mysql" version="1.0.0" modelVersion="7.12.0-004">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zk510sqyEeu5_vz_SfX0Jg" key="driver">
              <expression xmi:type="expression:Expression" xmi:id="_zk5108qyEeu5_vz_SfX0Jg" name="com.mysql.jdbc.Driver" content="com.mysql.jdbc.Driver" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zk511MqyEeu5_vz_SfX0Jg" key="url">
              <expression xmi:type="expression:Expression" xmi:id="_zk511cqyEeu5_vz_SfX0Jg" name="jdbc:mysql://127.0.0.1:3306/erp" content="jdbc:mysql://127.0.0.1:3306/erp" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zk511sqyEeu5_vz_SfX0Jg" key="script">
              <expression xmi:type="expression:Expression" xmi:id="_zk5118qyEeu5_vz_SfX0Jg" name="&lt;pattern-expression>" content="INSERT INTO `erp`.`faturas` (`data_fatura`, `id_cliente`, `data_pagamento`,&#xA;  `valorTotal`, `valorPago`, `id_pedido`)&#xA;  VALUES (now(), '${clientId}', NULL, '${valorTotal+''}', DEFAULT, '${pedido.id}')" type="TYPE_PATTERN" returnTypeFixed="true">
                <referencedElements xmi:type="expression:Expression" xmi:id="_a1z6UMq8Eeu5_vz_SfX0Jg" name="clientId" content="clientId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_a1z6Ucq8Eeu5_vz_SfX0Jg" name="clientId" content="clientId" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_a1z6Usq8Eeu5_vz_SfX0Jg" name="clientId" dataType="_3e4luLVdEeueyYy01cW2-g"/>
                  </referencedElements>
                </referencedElements>
                <referencedElements xmi:type="expression:Expression" xmi:id="_a1z6U8q8Eeu5_vz_SfX0Jg" name="valorTotal+''" content="valorTotal+''" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_a1z6VMq8Eeu5_vz_SfX0Jg" name="valorTotal" content="valorTotal" type="TYPE_VARIABLE" returnType="java.lang.Double">
                    <referencedElements xmi:type="process:Data" xmi:id="_a1z6Vcq8Eeu5_vz_SfX0Jg" name="valorTotal" dataType="_3e4lt7VdEeueyYy01cW2-g"/>
                  </referencedElements>
                </referencedElements>
                <referencedElements xmi:type="expression:Expression" xmi:id="_a1z6Vsq8Eeu5_vz_SfX0Jg" name="pedido.id" content="pedido.id" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_a1z6V8q8Eeu5_vz_SfX0Jg" name="pedido" content="pedido" type="TYPE_VARIABLE" returnType="com.company.model.Pedido">
                    <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_a1z6WMq8Eeu5_vz_SfX0Jg" name="pedido" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido"/>
                  </referencedElements>
                </referencedElements>
              </expression>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zk514cqyEeu5_vz_SfX0Jg" key="username">
              <expression xmi:type="expression:Expression" xmi:id="_zk514sqyEeu5_vz_SfX0Jg" name="root" content="root" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zk5148qyEeu5_vz_SfX0Jg" key="password">
              <expression xmi:type="expression:Expression" xmi:id="_zk515MqyEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zk515cqyEeu5_vz_SfX0Jg" key="separator">
              <expression xmi:type="expression:Expression" xmi:id="_zk515sqyEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zk5158qyEeu5_vz_SfX0Jg" key="outputType">
              <expression xmi:type="expression:Expression" xmi:id="_zk516MqyEeu5_vz_SfX0Jg" name="outputType" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zk516cqyEeu5_vz_SfX0Jg" key="wizardMode">
              <expression xmi:type="expression:Expression" xmi:id="_zk516sqyEeu5_vz_SfX0Jg" name="true" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </connectors>
        <connectors xmi:type="process:Connector" xmi:id="_HgOPkMrFEeuyAPbXmyzj0w" name="obter Ultimo ID" definitionId="database-mysql" event="ON_ENTER" definitionVersion="1.0.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_HgOPkcrFEeuyAPbXmyzj0w" definitionId="database-mysql" version="1.0.0" modelVersion="7.12.0-004">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HgOPksrFEeuyAPbXmyzj0w" key="driver">
              <expression xmi:type="expression:Expression" xmi:id="_HgOPk8rFEeuyAPbXmyzj0w" name="com.mysql.jdbc.Driver" content="com.mysql.jdbc.Driver" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HgOPlMrFEeuyAPbXmyzj0w" key="url">
              <expression xmi:type="expression:Expression" xmi:id="_HgOPlcrFEeuyAPbXmyzj0w" name="jdbc:mysql://localhost:3306/erp" content="jdbc:mysql://localhost:3306/erp" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HgOPlsrFEeuyAPbXmyzj0w" key="script">
              <expression xmi:type="expression:Expression" xmi:id="_HgOPl8rFEeuyAPbXmyzj0w" name="&lt;pattern-expression>" content="SELECT id FROM erp.faturas ORDER BY id DESC LIMIT 1" type="TYPE_PATTERN" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HgOPmMrFEeuyAPbXmyzj0w" key="username">
              <expression xmi:type="expression:Expression" xmi:id="_HgOPmcrFEeuyAPbXmyzj0w" name="root" content="root" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HgOPmsrFEeuyAPbXmyzj0w" key="password">
              <expression xmi:type="expression:Expression" xmi:id="_HgOPm8rFEeuyAPbXmyzj0w" name="" content="" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HgOPnMrFEeuyAPbXmyzj0w" key="separator">
              <expression xmi:type="expression:Expression" xmi:id="_HgOPncrFEeuyAPbXmyzj0w" content="" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HgOPnsrFEeuyAPbXmyzj0w" key="outputType">
              <expression xmi:type="expression:Expression" xmi:id="_HgOPn8rFEeuyAPbXmyzj0w" name="outputType" content="single" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HgOPoMrFEeuyAPbXmyzj0w" key="wizardMode">
              <expression xmi:type="expression:Expression" xmi:id="_HgOPocrFEeuyAPbXmyzj0w" name="true" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
          <outputs xmi:type="expression:Operation" xmi:id="_3rumoMrFEeuyAPbXmyzj0w">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3rumocrFEeuyAPbXmyzj0w" name="idFaturaInserida" content="idFaturaInserida" type="TYPE_VARIABLE" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_cuBZUMrhEeuCxpnbvV_u_Q" name="idFaturaInserida" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3rumo8rFEeuyAPbXmyzj0w" name="singleResult" content="singleResult" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
              <referencedElements xmi:type="definition:Output" xmi:id="_3rumpMrFEeuyAPbXmyzj0w" name="singleResult" type="java.lang.Object"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3rumpcrFEeuyAPbXmyzj0w" type="ASSIGNMENT"/>
          </outputs>
        </connectors>
        <loopCondition xmi:type="expression:Expression" xmi:id="_UtHpU8qyEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_UtHpVMqyEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UtHpVcqyEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_UtHpV8qyEeu5_vz_SfX0Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_UtHpVsqyEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_9oTA0MrHEeu5_vz_SfX0Jg" name="Inserir linhas de fatura" outgoing="_ITvtgMrhEeuCxpnbvV_u_Q" incoming="_9oYgYMrHEeu5_vz_SfX0Jg" type="STANDARD" testBefore="true">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_9oU2AcrHEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_9oU2AMrHEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_9oU2AsrHEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
        <connectors xmi:type="process:Connector" xmi:id="_6IBeYMrPEeu5_vz_SfX0Jg" name="insertLinhaFatura" definitionId="database-mysql" event="ON_ENTER" definitionVersion="1.0.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_6IBeYcrPEeu5_vz_SfX0Jg" definitionId="database-mysql" version="1.0.0" modelVersion="7.12.0-004">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_6IBeYsrPEeu5_vz_SfX0Jg" key="driver">
              <expression xmi:type="expression:Expression" xmi:id="_6IBeY8rPEeu5_vz_SfX0Jg" name="com.mysql.jdbc.Driver" content="com.mysql.jdbc.Driver" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_6IBeZMrPEeu5_vz_SfX0Jg" key="url">
              <expression xmi:type="expression:Expression" xmi:id="_6IBeZcrPEeu5_vz_SfX0Jg" name="jdbc:mysql://127.0.0.1:3306/erp" content="jdbc:mysql://127.0.0.1:3306/erp" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_6IBeZsrPEeu5_vz_SfX0Jg" key="script">
              <expression xmi:type="expression:Expression" xmi:id="_6IBeZ8rPEeu5_vz_SfX0Jg" name="&lt;pattern-expression>" content="INSERT INTO `erp`.`linhas_faturas` (`id_fatura`, `valor_servico`,&#xD;&#xA;  `data`, `id_intervencao`)&#xD;&#xA;  VALUES ('${idFaturaInserida+''}', '${valorContrato+''}', now(), '${listaIntervencoes.get(iterador).persistenceId+''}')" type="TYPE_PATTERN" returnTypeFixed="true">
                <referencedElements xmi:type="expression:Expression" xmi:id="_WGCXsMrsEeulHv9W8VSu9Q" name="idFaturaInserida+''" content="idFaturaInserida+''" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_WGCXscrsEeulHv9W8VSu9Q" name="idFaturaInserida" content="idFaturaInserida" type="TYPE_VARIABLE" returnType="java.lang.Integer">
                    <referencedElements xmi:type="process:Data" xmi:id="_WGCXssrsEeulHv9W8VSu9Q" name="idFaturaInserida" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
                  </referencedElements>
                </referencedElements>
                <referencedElements xmi:type="expression:Expression" xmi:id="_WGCXs8rsEeulHv9W8VSu9Q" name="valorContrato+''" content="valorContrato+''" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_WGCXtMrsEeulHv9W8VSu9Q" name="valorContrato" content="valorContrato" type="TYPE_VARIABLE" returnType="java.lang.Double">
                    <referencedElements xmi:type="process:Data" xmi:id="_WGCXtcrsEeulHv9W8VSu9Q" name="valorContrato" dataType="_3e4lt7VdEeueyYy01cW2-g"/>
                  </referencedElements>
                </referencedElements>
                <referencedElements xmi:type="expression:Expression" xmi:id="_WGCXtsrsEeulHv9W8VSu9Q" name="listaIntervencoes.get(iterador).persistenceId+''" content="listaIntervencoes.get(iterador).persistenceId+''" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_WGCXt8rsEeulHv9W8VSu9Q" name="iterador" content="iterador" type="TYPE_VARIABLE" returnType="java.lang.Integer">
                    <referencedElements xmi:type="process:Data" xmi:id="_WGCXuMrsEeulHv9W8VSu9Q" name="iterador" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
                  </referencedElements>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_WGCXucrsEeulHv9W8VSu9Q" name="listaIntervencoes" content="listaIntervencoes" type="TYPE_VARIABLE" returnType="java.util.List">
                    <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_WGCXusrsEeulHv9W8VSu9Q" name="listaIntervencoes" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Intervencao"/>
                  </referencedElements>
                </referencedElements>
              </expression>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_6IBea8rPEeu5_vz_SfX0Jg" key="username">
              <expression xmi:type="expression:Expression" xmi:id="_6IBebMrPEeu5_vz_SfX0Jg" name="root" content="root" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_6IBebcrPEeu5_vz_SfX0Jg" key="password">
              <expression xmi:type="expression:Expression" xmi:id="_6IBebsrPEeu5_vz_SfX0Jg" name="" content="" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_6IBeb8rPEeu5_vz_SfX0Jg" key="separator">
              <expression xmi:type="expression:Expression" xmi:id="_6IBecMrPEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_6IBeccrPEeu5_vz_SfX0Jg" key="outputType"/>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_6IBecsrPEeu5_vz_SfX0Jg" key="wizardMode">
              <expression xmi:type="expression:Expression" xmi:id="_6IBec8rPEeu5_vz_SfX0Jg" name="true" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
          <outputs xmi:type="expression:Operation" xmi:id="_eQG6UMrlEeuCxpnbvV_u_Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_eQG6UcrlEeuCxpnbvV_u_Q" content=""/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_eQG6UsrlEeuCxpnbvV_u_Q" name="resultset" content="resultset" type="CONNECTOR_OUTPUT_TYPE" returnType="java.sql.ResultSet">
              <referencedElements xmi:type="definition:Output" xmi:id="_eQG6U8rlEeuCxpnbvV_u_Q" name="resultset" type="java.sql.ResultSet"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_eQG6VMrlEeuCxpnbvV_u_Q" type="ASSIGNMENT"/>
          </outputs>
        </connectors>
        <operations xmi:type="expression:Operation" xmi:id="_A1HjUMriEeuCxpnbvV_u_Q">
          <leftOperand xmi:type="expression:Expression" xmi:id="_A1HjUcriEeuCxpnbvV_u_Q" name="iterador" content="iterador" type="TYPE_VARIABLE" returnType="java.lang.Integer">
            <referencedElements xmi:type="process:Data" xmi:id="_BYt_oMriEeuCxpnbvV_u_Q" name="iterador" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_A1HjUsriEeuCxpnbvV_u_Q" name="newScript()" content="return iterador + 1" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
            <referencedElements xmi:type="process:Data" xmi:id="_5MO3oMrnEeuCxpnbvV_u_Q" name="iterador" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_A1HjU8riEeuCxpnbvV_u_Q" type="ASSIGNMENT"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_9oU2A8rHEeu5_vz_SfX0Jg" name="loopWhile()" content="iterador &lt; sizeLista" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_-v1R0MrhEeuCxpnbvV_u_Q" name="iterador" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
          <referencedElements xmi:type="process:Data" xmi:id="_-v1R0crhEeuCxpnbvV_u_Q" name="sizeLista" dataType="_3e4ltbVdEeueyYy01cW2-g"/>
        </loopCondition>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_9oU2BMrHEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9oU2BcrHEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_9oU2B8rHEeu5_vz_SfX0Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_9oU2BsrHEeu5_vz_SfX0Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_ISnFEMrhEeuCxpnbvV_u_Q" name="End5" incoming="_ITvtgMrhEeuCxpnbvV_u_Q">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ISvA4crhEeuCxpnbvV_u_Q" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ISvA4MrhEeuCxpnbvV_u_Q" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ISvn8MrhEeuCxpnbvV_u_Q" name="" content="" returnTypeFixed="true"/>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Wz6TgMquEeu5_vz_SfX0Jg" name="pedido" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Pedido">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Wz66kMquEeu5_vz_SfX0Jg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_2knsEMquEeu5_vz_SfX0Jg" name="listaIntervencoes" multiple="true" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Intervencao">
        <defaultValue xmi:type="expression:Expression" xmi:id="_2knsEcquEeu5_vz_SfX0Jg" name="" content="" interpreter="GROOVY"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_3znucMqxEeu5_vz_SfX0Jg" name="valorContrato" dataType="_3e4lt7VdEeueyYy01cW2-g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_3znuccqxEeu5_vz_SfX0Jg" content="" returnType="java.lang.Double"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6xyIsMqxEeu5_vz_SfX0Jg" name="valorTotal" dataType="_3e4lt7VdEeueyYy01cW2-g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6xyIscqxEeu5_vz_SfX0Jg" content="" returnType="java.lang.Double"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_BFlpEMqyEeu5_vz_SfX0Jg" name="clientId" dataType="_3e4luLVdEeueyYy01cW2-g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_BFlpEcqyEeu5_vz_SfX0Jg" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_V_cEcMrAEeu5_vz_SfX0Jg" name="idFaturaInserida" dataType="_3e4ltbVdEeueyYy01cW2-g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_V_cEccrAEeu5_vz_SfX0Jg" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_n2m3UMrhEeuCxpnbvV_u_Q" name="iterador" dataType="_3e4ltbVdEeueyYy01cW2-g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_n2m3UcrhEeuCxpnbvV_u_Q" name="0" content="0" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_rfm-UMrhEeuCxpnbvV_u_Q" name="sizeLista" dataType="_3e4ltbVdEeueyYy01cW2-g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_rfm-UcrhEeuCxpnbvV_u_Q" name="0" content="0" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_E4FiIMrlEeuCxpnbvV_u_Q" name="intervencao" dataType="_3e4lu7VdEeueyYy01cW2-g" className="com.company.model.Intervencao">
        <defaultValue xmi:type="expression:Expression" xmi:id="_E4FiIcrlEeuCxpnbvV_u_Q" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_31Vij8qtEeu5_vz_SfX0Jg">
        <targetForm xmi:type="expression:Expression" xmi:id="_z5sAsMt7Eeuskqtd-X0x2w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_31VikcqtEeu5_vz_SfX0Jg">
        <targetForm xmi:type="expression:Expression" xmi:id="_31ViksqtEeu5_vz_SfX0Jg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Hjnj0MqvEeu5_vz_SfX0Jg" target="_LS6gEMqvEeu5_vz_SfX0Jg" source="_L51LkMquEeu5_vz_SfX0Jg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HjoK4MqvEeu5_vz_SfX0Jg"/>
        <condition xmi:type="expression:Expression" xmi:id="_HjoK4cqvEeu5_vz_SfX0Jg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UqMGkMqxEeu5_vz_SfX0Jg" target="_UqDjsMqxEeu5_vz_SfX0Jg" source="_LS6gEMqvEeu5_vz_SfX0Jg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UqMGkcqxEeu5_vz_SfX0Jg"/>
        <condition xmi:type="expression:Expression" xmi:id="_UqMGksqxEeu5_vz_SfX0Jg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UtL6wMqyEeu5_vz_SfX0Jg" target="_UtHCQMqyEeu5_vz_SfX0Jg" source="_UqDjsMqxEeu5_vz_SfX0Jg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UtL6wcqyEeu5_vz_SfX0Jg"/>
        <condition xmi:type="expression:Expression" xmi:id="_UtL6wsqyEeu5_vz_SfX0Jg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9oYgYMrHEeu5_vz_SfX0Jg" target="_9oTA0MrHEeu5_vz_SfX0Jg" source="_UtHCQMqyEeu5_vz_SfX0Jg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9oYgYcrHEeu5_vz_SfX0Jg"/>
        <condition xmi:type="expression:Expression" xmi:id="_9oYgYsrHEeu5_vz_SfX0Jg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ITvtgMrhEeuCxpnbvV_u_Q" target="_ISnFEMrhEeuCxpnbvV_u_Q" source="_9oTA0MrHEeu5_vz_SfX0Jg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ITvtgcrhEeuCxpnbvV_u_Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_ITwUkMrhEeuCxpnbvV_u_Q" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_31Vik8qtEeu5_vz_SfX0Jg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_31VigMqtEeu5_vz_SfX0Jg">
        <name xmi:type="expression:Expression" xmi:id="_31VigcqtEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_31VigsqtEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_31Vig8qtEeu5_vz_SfX0Jg">
        <name xmi:type="expression:Expression" xmi:id="_31VihMqtEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_31VihcqtEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_31VihsqtEeu5_vz_SfX0Jg">
        <name xmi:type="expression:Expression" xmi:id="_31Vih8qtEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_31ViiMqtEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_31ViicqtEeu5_vz_SfX0Jg">
        <name xmi:type="expression:Expression" xmi:id="_31ViisqtEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_31Vii8qtEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_31VijMqtEeu5_vz_SfX0Jg">
        <name xmi:type="expression:Expression" xmi:id="_31VijcqtEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_31VijsqtEeu5_vz_SfX0Jg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_3e4ls7VdEeueyYy01cW2-g" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_3e4ltLVdEeueyYy01cW2-g" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_3e4ltbVdEeueyYy01cW2-g" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_3e4ltrVdEeueyYy01cW2-g" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_3e4lt7VdEeueyYy01cW2-g" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_3e4luLVdEeueyYy01cW2-g" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_3e4lubVdEeueyYy01cW2-g" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_3e4lurVdEeueyYy01cW2-g" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_3e4lu7VdEeueyYy01cW2-g" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_3e4lvLVdEeueyYy01cW2-g" type="Process" element="_3e3-gLVdEeueyYy01cW2-g" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_3e4lvbVdEeueyYy01cW2-g" type="2007" element="_3e3-gbVdEeueyYy01cW2-g">
      <children xmi:type="notation:DecorationNode" xmi:id="_3e4lvrVdEeueyYy01cW2-g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_3e4lv7VdEeueyYy01cW2-g" type="7001">
        <children xmi:type="notation:Node" xmi:id="_go524LVeEeueyYy01cW2-g" type="3007" element="_go5P0LVeEeueyYy01cW2-g">
          <children xmi:type="notation:DecorationNode" xmi:id="_go525bVeEeueyYy01cW2-g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_go525rVeEeueyYy01cW2-g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_sGAW5LVfEeueyYy01cW2-g" type="3008" element="_sGAW4LVfEeueyYy01cW2-g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_sGAW5rVfEeueyYy01cW2-g" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sGAW57VfEeueyYy01cW2-g" y="11"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sGAW5bVfEeueyYy01cW2-g" x="384" y="71" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1klxMLVfEeueyYy01cW2-g" type="3027" element="_1klKILVfEeueyYy01cW2-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1klxMrVfEeueyYy01cW2-g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1klxMbVfEeueyYy01cW2-g" x="483" y="14" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_33XvVLVjEeueyYy01cW2-g" type="3008" element="_33XvULVjEeueyYy01cW2-g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_33XvVrVjEeueyYy01cW2-g" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_33XvV7VjEeueyYy01cW2-g" x="66" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_33XvVbVjEeueyYy01cW2-g" x="662" y="71" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_glFGSMOVEeu9G7kJfwO5Gg" type="3027" element="_glEfMMOVEeu9G7kJfwO5Gg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_glFGSsOVEeu9G7kJfwO5Gg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_glFGScOVEeu9G7kJfwO5Gg" x="156" y="53" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xsBIUMsEEeuVH99PbiCVIw" type="3016" element="_xr-sEMsEEeuVH99PbiCVIw" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_xsBvYMsEEeuVH99PbiCVIw" type="5031">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xsBvYcsEEeuVH99PbiCVIw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsBIUcsEEeuVH99PbiCVIw" x="51" y="82"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_go524bVeEeueyYy01cW2-g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_go524rVeEeueyYy01cW2-g" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_go5247VeEeueyYy01cW2-g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_go5257VeEeueyYy01cW2-g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_go525LVeEeueyYy01cW2-g" x="48" y="298" width="1607" height="167"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_hEbVQLVeEeueyYy01cW2-g" type="3007" element="_hEauMLVeEeueyYy01cW2-g">
          <children xmi:type="notation:DecorationNode" xmi:id="_hEbVRbVeEeueyYy01cW2-g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_hEbVRrVeEeueyYy01cW2-g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_6L1sULVjEeueyYy01cW2-g" type="3027" element="_6L1FQLVjEeueyYy01cW2-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6L1sUrVjEeueyYy01cW2-g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6L1sUbVjEeueyYy01cW2-g" x="704" y="42" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8mOrILVjEeueyYy01cW2-g" type="3003" element="_8mOEELVjEeueyYy01cW2-g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_8mOrIrVjEeueyYy01cW2-g" visible="false" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8mOrI7VjEeueyYy01cW2-g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8mOrIbVjEeueyYy01cW2-g" x="1296" y="55"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ohd8NcquEeu5_vz_SfX0Jg" type="3063" element="_OhdVIMquEeu5_vz_SfX0Jg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ohd8N8quEeu5_vz_SfX0Jg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ohd8NsquEeu5_vz_SfX0Jg" x="902" y="34" width="175" height="86"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NBFqUMt5Eeuskqtd-X0x2w" type="3027" element="_NBD1IMt5Eeuskqtd-X0x2w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NBGRYct5Eeuskqtd-X0x2w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NBGRYMt5Eeuskqtd-X0x2w" x="1114" y="43" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_hEbVQbVeEeueyYy01cW2-g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_hEbVQrVeEeueyYy01cW2-g" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_hEbVQ7VeEeueyYy01cW2-g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_hEbVR7VeEeueyYy01cW2-g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hEbVRLVeEeueyYy01cW2-g" x="28" y="167" width="1330" height="178"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_3e4lz7VdEeueyYy01cW2-g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_3e4l0LVdEeueyYy01cW2-g" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_3e4l0bVdEeueyYy01cW2-g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_3e4l0rVdEeueyYy01cW2-g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3e4l07VdEeueyYy01cW2-g" width="1459" height="654"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_312f4MqtEeu5_vz_SfX0Jg" type="2007" element="_3yWf8MqtEeu5_vz_SfX0Jg">
      <children xmi:type="notation:DecorationNode" xmi:id="_313G8MqtEeu5_vz_SfX0Jg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_313G8cqtEeu5_vz_SfX0Jg" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_L55dAMquEeu5_vz_SfX0Jg" type="3002" element="_L51LkMquEeu5_vz_SfX0Jg" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_L55dAsquEeu5_vz_SfX0Jg" visible="false" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_L55dA8quEeu5_vz_SfX0Jg" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L55dAcquEeu5_vz_SfX0Jg" x="79" y="110"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_LS7HIMqvEeu5_vz_SfX0Jg" type="3027" element="_LS6gEMqvEeu5_vz_SfX0Jg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_LS7HIsqvEeu5_vz_SfX0Jg" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LS7HIcqvEeu5_vz_SfX0Jg" x="198" y="100" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_UqFY4MqxEeu5_vz_SfX0Jg" type="3027" element="_UqDjsMqxEeu5_vz_SfX0Jg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_UqF_8MqxEeu5_vz_SfX0Jg" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UqFY4cqxEeu5_vz_SfX0Jg" x="378" y="101" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_UtIQYMqyEeu5_vz_SfX0Jg" type="3027" element="_UtHCQMqyEeu5_vz_SfX0Jg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_UtIQYsqyEeu5_vz_SfX0Jg" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UtIQYcqyEeu5_vz_SfX0Jg" x="583" y="104" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_9oVdEMrHEeu5_vz_SfX0Jg" type="3027" element="_9oTA0MrHEeu5_vz_SfX0Jg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_9oWEIMrHEeu5_vz_SfX0Jg" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9oVdEcrHEeu5_vz_SfX0Jg" x="787" y="105" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_ITiSIMrhEeuCxpnbvV_u_Q" type="3003" element="_ISnFEMrhEeuCxpnbvV_u_Q" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_ITi5MMrhEeuCxpnbvV_u_Q" visible="false" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_ITi5McrhEeuCxpnbvV_u_Q" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ITiSIcrhEeuCxpnbvV_u_Q" x="1041" y="119"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_312f4cqtEeu5_vz_SfX0Jg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_312f4sqtEeu5_vz_SfX0Jg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_312f48qtEeu5_vz_SfX0Jg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_313G8sqtEeu5_vz_SfX0Jg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_312f5MqtEeu5_vz_SfX0Jg" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_3e4l1LVdEeueyYy01cW2-g"/>
    <edges xmi:type="notation:Connector" xmi:id="_qh9xQLVfEeueyYy01cW2-g" type="4001" element="_qh9KMLVfEeueyYy01cW2-g" source="_glFGSMOVEeu9G7kJfwO5Gg" target="_sGAW5LVfEeueyYy01cW2-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qh9xQ7VfEeueyYy01cW2-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qh9xRLVfEeueyYy01cW2-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qh9xQbVfEeueyYy01cW2-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qh9xQrVfEeueyYy01cW2-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1kqCoLVfEeueyYy01cW2-g" type="4001" element="_1ko0gLVfEeueyYy01cW2-g" source="_sGAW5LVfEeueyYy01cW2-g" target="_1klxMLVfEeueyYy01cW2-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1kqCo7VfEeueyYy01cW2-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1kqCpLVfEeueyYy01cW2-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1kqCobVfEeueyYy01cW2-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1kqCorVfEeueyYy01cW2-g" points="[0, -21, -98, 44]$[0, -59, -98, 6]$[78, -59, -20, 6]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ez2-cLVlEeueyYy01cW2-g" id="(0.14285714285714285,0.18571428571428572)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1LSjkLVjEeueyYy01cW2-g" type="4001" element="_1LLO0LVjEeueyYy01cW2-g" source="_sGAW5LVfEeueyYy01cW2-g" target="_33XvVLVjEeueyYy01cW2-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1LSjk7VjEeueyYy01cW2-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1LSjlLVjEeueyYy01cW2-g" x="-107" y="14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1LSjkbVjEeueyYy01cW2-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1LSjkrVjEeueyYy01cW2-g" points="[21, -21, -658, 0]$[658, -21, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1_rN4LVjEeueyYy01cW2-g" id="(0.5116279069767442,0.9767441860465116)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6L4Ik7VjEeueyYy01cW2-g" type="4001" element="_6L4IkLVjEeueyYy01cW2-g" source="_33XvVLVjEeueyYy01cW2-g" target="_6L1sULVjEeueyYy01cW2-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6L4voLVjEeueyYy01cW2-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6L4vobVjEeueyYy01cW2-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6L4IlLVjEeueyYy01cW2-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6L4IlbVjEeueyYy01cW2-g" points="[9, 13, -93, -128]$[9, 141, -93, 0]$[52, 141, -50, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_X2L1ULVkEeueyYy01cW2-g" id="(0.4418604651162791,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3HX188kQEeuHZvio8DfM6Q" type="4001" element="_3HX18MkQEeuHZvio8DfM6Q" source="_1klxMLVfEeueyYy01cW2-g" target="_33XvVLVjEeueyYy01cW2-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3HX19skQEeuHZvio8DfM6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3HX198kQEeuHZvio8DfM6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3HX19MkQEeuHZvio8DfM6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3HX19ckQEeuHZvio8DfM6Q" points="[0, 0, -60, -43]$[60, 0, 0, -43]$[60, 22, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3HX1-MkQEeuHZvio8DfM6Q" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HlCFw8kSEeuHZvio8DfM6Q" type="4001" element="_HlCFwMkSEeuHZvio8DfM6Q" source="_6L1sULVjEeueyYy01cW2-g" target="_Ohd8NcquEeu5_vz_SfX0Jg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HlCFxskSEeuHZvio8DfM6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HlCFx8kSEeuHZvio8DfM6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HlCFxMkSEeuHZvio8DfM6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HlCFxckSEeuHZvio8DfM6Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HjpZAMqvEeu5_vz_SfX0Jg" type="4001" element="_Hjnj0MqvEeu5_vz_SfX0Jg" source="_L55dAMquEeu5_vz_SfX0Jg" target="_LS7HIMqvEeu5_vz_SfX0Jg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HjqAEMqvEeu5_vz_SfX0Jg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HjqAEcqvEeu5_vz_SfX0Jg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HjpZAcqvEeu5_vz_SfX0Jg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HjpZAsqvEeu5_vz_SfX0Jg" points="[-1, -16, -99, 2]$[89, -19, -9, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Hjr1QMqvEeu5_vz_SfX0Jg" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Hjr1QcqvEeu5_vz_SfX0Jg" id="(0.09,0.44)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UqMtoMqxEeu5_vz_SfX0Jg" type="4001" element="_UqMGkMqxEeu5_vz_SfX0Jg" source="_LS7HIMqvEeu5_vz_SfX0Jg" target="_UqFY4MqxEeu5_vz_SfX0Jg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UqMto8qxEeu5_vz_SfX0Jg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UqNUsMqxEeu5_vz_SfX0Jg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UqMtocqxEeu5_vz_SfX0Jg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UqMtosqxEeu5_vz_SfX0Jg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UtMh0MqyEeu5_vz_SfX0Jg" type="4001" element="_UtL6wMqyEeu5_vz_SfX0Jg" source="_UqFY4MqxEeu5_vz_SfX0Jg" target="_UtIQYMqyEeu5_vz_SfX0Jg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UtMh08qyEeu5_vz_SfX0Jg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UtMh1MqyEeu5_vz_SfX0Jg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UtMh0cqyEeu5_vz_SfX0Jg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UtMh0sqyEeu5_vz_SfX0Jg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sNZpgMrCEeuyAPbXmyzj0w" type="4001" element="_sNUJ8MrCEeuyAPbXmyzj0w" source="_Ohd8NcquEeu5_vz_SfX0Jg" target="_NBFqUMt5Eeuskqtd-X0x2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sNa3oMrCEeuyAPbXmyzj0w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sNa3ocrCEeuyAPbXmyzj0w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sNZpgcrCEeuyAPbXmyzj0w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sNZpgsrCEeuyAPbXmyzj0w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_sNcs0MrCEeuyAPbXmyzj0w" id="(1.0,0.3488372093023256)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9oYgY8rHEeu5_vz_SfX0Jg" type="4001" element="_9oYgYMrHEeu5_vz_SfX0Jg" source="_UtIQYMqyEeu5_vz_SfX0Jg" target="_9oVdEMrHEeu5_vz_SfX0Jg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9oZHcMrHEeu5_vz_SfX0Jg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9oZHccrHEeu5_vz_SfX0Jg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9oYgZMrHEeu5_vz_SfX0Jg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9oYgZcrHEeu5_vz_SfX0Jg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ITw7oMrhEeuCxpnbvV_u_Q" type="4001" element="_ITvtgMrhEeuCxpnbvV_u_Q" source="_9oVdEMrHEeu5_vz_SfX0Jg" target="_ITiSIMrhEeuCxpnbvV_u_Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ITxisMrhEeuCxpnbvV_u_Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ITxiscrhEeuCxpnbvV_u_Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ITw7ocrhEeuCxpnbvV_u_Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ITw7osrhEeuCxpnbvV_u_Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NBNmIMt5Eeuskqtd-X0x2w" type="4001" element="_NBM_EMt5Eeuskqtd-X0x2w" source="_NBFqUMt5Eeuskqtd-X0x2w" target="_8mOrILVjEeueyYy01cW2-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NBONMMt5Eeuskqtd-X0x2w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NBONMct5Eeuskqtd-X0x2w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NBNmIct5Eeuskqtd-X0x2w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NBNmIst5Eeuskqtd-X0x2w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_j6IMsMt7Eeuskqtd-X0x2w" type="4001" element="_j6HloMt7Eeuskqtd-X0x2w" source="_xsBIUMsEEeuVH99PbiCVIw" target="_glFGSMOVEeu9G7kJfwO5Gg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j6IMs8t7Eeuskqtd-X0x2w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j6IMtMt7Eeuskqtd-X0x2w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j6IMsct7Eeuskqtd-X0x2w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_j6IMsst7Eeuskqtd-X0x2w" points="[-1, -15, -156, 4]$[75, -10, -80, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_j6IzwMt7Eeuskqtd-X0x2w" id="(1.0,1.0)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
